spring:
  application:
    name: rest-with-spring-boot-and-java-erudio

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gerenciador_animes?useTimezone=true&serverTimezone=UTC
    username: joel
    password: fullmetal

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: false

    open-in-view: false

logging:
  level:
    root: WARN
    #3br.com.rest-with-spring-boot-and-java-erudio: WARN